name: release
run-name: "Release ${{github.ref_name}} by @${{github.actor}}"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    environment:
      name: release
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0  # fetch all commits, tags and branches
      - name: "Setup Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.22.10"
      - name: "Docker login"
        run: "echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{github.actor}} --password-stdin"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Run GoReleaser"
        uses: "goreleaser/goreleaser-action@v6"
        with:
          distribution: "goreleaser"
          version: "~> v2"  # goreleaser version
          args: "release --clean"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Setup Pages"
        uses: "actions/configure-pages@v5"
      - name: "Build Pages"
        run: |
          go run ./cmd/tetris-wasm --gen-static --static-prefix /go-tetris
          GOOS=js GOARCH=wasm go build -o web/static/web/app.wasm ./cmd/tetris-wasm
      - name: "Upload pages artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: 'web/static'
      - name: "Deploy to GitHub Pages"
        uses: "actions/deploy-pages@v4"
